// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAL40H_lCtHntOd5ybVdlXuEcbHJXqxmw',
    appId: '1:103134450272:web:cce229f29d6b7783442905',
    messagingSenderId: '103134450272',
    projectId: 'fir-e25b2',
    authDomain: 'fir-e25b2.firebaseapp.com',
    storageBucket: 'fir-e25b2.appspot.com',
    measurementId: 'G-L0T5FM155F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1RS3Q75gVR6XRIdgppERt-y9TIMF2yF8',
    appId: '1:103134450272:android:6c126b0f6e1250b8442905',
    messagingSenderId: '103134450272',
    projectId: 'fir-e25b2',
    storageBucket: 'fir-e25b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA78puT5DMQMcLCG__MdqEPoJms6FTfZ54',
    appId: '1:103134450272:ios:8a5ec454dc281efa442905',
    messagingSenderId: '103134450272',
    projectId: 'fir-e25b2',
    storageBucket: 'fir-e25b2.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA78puT5DMQMcLCG__MdqEPoJms6FTfZ54',
    appId: '1:103134450272:ios:8a5ec454dc281efa442905',
    messagingSenderId: '103134450272',
    projectId: 'fir-e25b2',
    storageBucket: 'fir-e25b2.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAL40H_lCtHntOd5ybVdlXuEcbHJXqxmw',
    appId: '1:103134450272:web:6c1deff09c543936442905',
    messagingSenderId: '103134450272',
    projectId: 'fir-e25b2',
    authDomain: 'fir-e25b2.firebaseapp.com',
    storageBucket: 'fir-e25b2.appspot.com',
    measurementId: 'G-MWSSMWZFJ9',
  );

}